/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			colors: {
				primary: "var(--color-primary)",
				secondary: "var(--color-secondary)",
				tertiary: "var(--color-tertiary)",
				"backgorund-color": "var(--color-background)",
				"mocha-base": "#1e1e2e",
				"mocha-mantle": "#181825",
				"mocha-crust": "#11111b",
				"mocha-surface0": "#313244",
				"mocha-surface1": "#45475a",
				"mocha-surface2": "#585b70",
				"mocha-overlay0": "#6c7086",
				"mocha-overlay1": "#7f849c",
				"mocha-overlay2": "#9399b2",
				"mocha-subtext0": "#a6adc8",
				"mocha-subtext1": "#bac2de",
				"mocha-text": "#cdd6f4",
				"mocha-lavender": "#b4befe",
				"mocha-blue": "#89b4fa",
				"mocha-sapphire": "#74c7ec",
				"mocha-sky": "#89dceb",
				"mocha-teal": "#94e2d5",
				"mocha-green": "#a6e3a1",
				"mocha-yellow": "#f9e2af",
				"mocha-peach": "#fab387",
				"mocha-maroon": "#eba0ac",
				"mocha-red": "#f38ba8",
				"mocha-mauve": "#cba6f7",
				"mocha-pink": "#f5c2e7",
				"mocha-flamingo": "#f2cdcd",
				"mocha-rosewater": "#f5e0dc",
			},
			fontFamily: {
				sans: [
					"Nunito",
					"Inter",
					"system-ui",
					"Avenir",
					"Helvetica",
					"Arial",
					"sans-serif",
				],
			},
		},
	},
	plugins: [],
};
