/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			colors: {
				/* CSS-vars de tu diseño */
				primary: "var(--color-primary)",
				secondary: "var(--color-secondary)",
				tertiary: "var(--color-tertiary)",
				"backgorund-color": "var(--color-background)",

				/* Catppuccin - Mocha (ya presente) */
				"mocha-base": "#1e1e2e",
				"mocha-mantle": "#181825",
				"mocha-crust": "#11111b",
				"mocha-surface0": "#313244",
				"mocha-surface1": "#45475a",
				"mocha-surface2": "#585b70",
				"mocha-overlay0": "#6c7086",
				"mocha-overlay1": "#7f849c",
				"mocha-overlay2": "#9399b2",
				"mocha-subtext0": "#a6adc8",
				"mocha-subtext1": "#bac2de",
				"mocha-text": "#cdd6f4",
				"mocha-lavender": "#b4befe",
				"mocha-blue": "#89b4fa",
				"mocha-sapphire": "#74c7ec",
				"mocha-sky": "#89dceb",
				"mocha-teal": "#94e2d5",
				"mocha-green": "#a6e3a1",
				"mocha-yellow": "#f9e2af",
				"mocha-peach": "#fab387",
				"mocha-maroon": "#eba0ac",
				"mocha-red": "#f38ba8",
				"mocha-mauve": "#cba6f7",
				"mocha-pink": "#f5c2e7",
				"mocha-flamingo": "#f2cdcd",
				"mocha-rosewater": "#f5e0dc",

				/* Nord – Polar Night, Snow Storm, Frost, Aurora */
				nord0: "#2E3440",
				nord1: "#3B4252",
				nord2: "#434C5E",
				nord3: "#4C566A",
				nord4: "#D8DEE9",
				nord5: "#E5E9F0",
				nord6: "#ECEFF4",
				nord7: "#8FBCBB",
				nord8: "#88C0D0",
				nord9: "#81A1C1",
				nord10: "#5E81AC",
				nord11: "#BF616A",
				nord12: "#D08770",
				nord13: "#EBCB8B",
				nord14: "#A3BE8C",
				nord15: "#B48EAD",
			},
			fontFamily: {
				sans: [
					"Nunito",
					"Inter",
					"system-ui",
					"Avenir",
					"Helvetica",
					"Arial",
					"sans-serif",
				],
			},
		},
	},
	plugins: [],
};
